### ISSUE TITLE
Add "durability" to potion bottles

### ISSUE THREAD

**Issue by xrtariq2594** [Terasology/Potions#1]
Currently, when a potion is drunk, the original bottle is destroyed. A nice extension to the potion drinking system would be to allow for a bottle to be used multiple times before discarded. In other words, if a health potion were to be drunk, an empty potion bottle would be returned as long as the remaining durability was high enough.

We likely need one or two new components for this, and tweaking of a few systems. Probably also need add defaults and modify the potion crafting system in Alchemy.

So we need at least the following:
- Name of the old potion bottle's prefab.
- Durability of the potion bottle.
- Durability cost per potion drink.
- Is the potion bottle unbreakable?

**Comment by AWebb3701** [comment]
the easiest way to handle this imo would be to just give potions themselves a durability value, then return a bottle with a slightly lower value when used, returning nothing if the durability reaches 0.

Personally, the idea of durability degradation on a potion bottle seems silly, since you wouldn't be able to stack your empty bottles or your potions anymore.

**Comment by xrtariq2594** [comment]
Currently, I'm thinking of using the DurabilityComponent (from the Durability module). I'll add in the prefab, cost, and boolean flag to the potion component itself.

**Comment by xrtariq2594** [comment]
As of PR #3, durability has been added.
